"""diagnosis standard

Revision ID: 3e8e69720852
Revises: ee0e92c453fe
Create Date: 2019-07-15 15:20:18.475741

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e8e69720852'
down_revision = 'ee0e92c453fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bearing_evaluate_standard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bpfi_lv1', sa.Float(), nullable=True),
    sa.Column('bpfi_lv2', sa.Float(), nullable=True),
    sa.Column('bpfi_lv3', sa.Float(), nullable=True),
    sa.Column('bsf_lv1', sa.Float(), nullable=True),
    sa.Column('bsf_lv2', sa.Float(), nullable=True),
    sa.Column('bsf_lv3', sa.Float(), nullable=True),
    sa.Column('bpfo_lv1', sa.Float(), nullable=True),
    sa.Column('bpfo_lv2', sa.Float(), nullable=True),
    sa.Column('bpfo_lv3', sa.Float(), nullable=True),
    sa.Column('ftf_lv1', sa.Float(), nullable=True),
    sa.Column('ftf_lv2', sa.Float(), nullable=True),
    sa.Column('ftf_lv3', sa.Float(), nullable=True),
    sa.Column('har5_lv1', sa.Float(), nullable=True),
    sa.Column('har5_lv2', sa.Float(), nullable=True),
    sa.Column('har5_lv3', sa.Float(), nullable=True),
    sa.Column('md_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('power_evaluate_standard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('i_imbalance_lv1', sa.Float(), nullable=True),
    sa.Column('i_imbalance_lv2', sa.Float(), nullable=True),
    sa.Column('i_imbalance_lv3', sa.Float(), nullable=True),
    sa.Column('u_imbalance_lv1', sa.Float(), nullable=True),
    sa.Column('u_imbalance_lv2', sa.Float(), nullable=True),
    sa.Column('u_imbalance_lv3', sa.Float(), nullable=True),
    sa.Column('uthd_lv1', sa.Float(), nullable=True),
    sa.Column('uthd_lv2', sa.Float(), nullable=True),
    sa.Column('uthd_lv3', sa.Float(), nullable=True),
    sa.Column('ithd_lv1', sa.Float(), nullable=True),
    sa.Column('ithd_lv2', sa.Float(), nullable=True),
    sa.Column('ithd_lv3', sa.Float(), nullable=True),
    sa.Column('uhar_odd_lv1', sa.Float(), nullable=True),
    sa.Column('uhar_odd_lv2', sa.Float(), nullable=True),
    sa.Column('uhar_odd_lv3', sa.Float(), nullable=True),
    sa.Column('uhar_even_lv1', sa.Float(), nullable=True),
    sa.Column('uhar_even_lv2', sa.Float(), nullable=True),
    sa.Column('uhar_even_lv3', sa.Float(), nullable=True),
    sa.Column('power_factor_lv1', sa.Float(), nullable=True),
    sa.Column('power_factor_lv2', sa.Float(), nullable=True),
    sa.Column('power_factor_lv3', sa.Float(), nullable=True),
    sa.Column('md_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('rotor_evaluate_standard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slip', sa.Float(), nullable=True),
    sa.Column('sideband_lv1', sa.Float(), nullable=True),
    sa.Column('sideband_lv2', sa.Float(), nullable=True),
    sa.Column('sideband_lv3', sa.Float(), nullable=True),
    sa.Column('md_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('stator_evaluate_standard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('i_imbalance_lv1', sa.Float(), nullable=True),
    sa.Column('i_imbalance_lv2', sa.Float(), nullable=True),
    sa.Column('i_imbalance_lv3', sa.Float(), nullable=True),
    sa.Column('u_imbalance_lv1', sa.Float(), nullable=True),
    sa.Column('u_imbalance_lv2', sa.Float(), nullable=True),
    sa.Column('u_imbalance_lv3', sa.Float(), nullable=True),
    sa.Column('irms_imbalance_lv1', sa.Float(), nullable=True),
    sa.Column('irms_imbalance_lv2', sa.Float(), nullable=True),
    sa.Column('irms_imbalance_lv3', sa.Float(), nullable=True),
    sa.Column('har3_lv1', sa.Float(), nullable=True),
    sa.Column('har3_lv2', sa.Float(), nullable=True),
    sa.Column('har3_lv3', sa.Float(), nullable=True),
    sa.Column('uz_type', sa.SmallInteger(), nullable=True),
    sa.Column('uz_imbalance_lv1', sa.Float(), nullable=True),
    sa.Column('uz_imbalance_lv2', sa.Float(), nullable=True),
    sa.Column('uz_imbalance_lv3', sa.Float(), nullable=True),
    sa.Column('iz_type', sa.SmallInteger(), nullable=True),
    sa.Column('iz_imbalance_lv1', sa.Float(), nullable=True),
    sa.Column('iz_imbalance_lv2', sa.Float(), nullable=True),
    sa.Column('iz_imbalance_lv3', sa.Float(), nullable=True),
    sa.Column('md_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('motor_evaluate_standard')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('elecdata_2', 'wvolt',
               existing_type=sa.BLOB(),
               nullable=True)
    op.alter_column('elecdata_2', 'vvolt',
               existing_type=sa.BLOB(),
               nullable=True)
    op.alter_column('elecdata_2', 'uvolt',
               existing_type=sa.BLOB(),
               nullable=True)
    op.alter_column('elecdata_1', 'wvolt',
               existing_type=sa.BLOB(),
               nullable=True)
    op.alter_column('elecdata_1', 'vvolt',
               existing_type=sa.BLOB(),
               nullable=True)
    op.alter_column('elecdata_1', 'uvolt',
               existing_type=sa.BLOB(),
               nullable=True)
    op.alter_column('elecdata_0', 'wvolt',
               existing_type=sa.BLOB(),
               nullable=True)
    op.alter_column('elecdata_0', 'vvolt',
               existing_type=sa.BLOB(),
               nullable=True)
    op.alter_column('elecdata_0', 'uvolt',
               existing_type=sa.BLOB(),
               nullable=True)
    op.create_table('motor_evaluate_standard',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('imbalance_lv1', mysql.FLOAT(), nullable=True),
    sa.Column('imbalance_lv2', mysql.FLOAT(), nullable=True),
    sa.Column('imbalance_lv3', mysql.FLOAT(), nullable=True),
    sa.Column('thd_lv1', mysql.FLOAT(), nullable=True),
    sa.Column('thd_lv2', mysql.FLOAT(), nullable=True),
    sa.Column('thd_lv3', mysql.FLOAT(), nullable=True),
    sa.Column('brb_lv1', mysql.FLOAT(), nullable=True),
    sa.Column('brb_lv2', mysql.FLOAT(), nullable=True),
    sa.Column('brb_lv3', mysql.FLOAT(), nullable=True),
    sa.Column('bpfi_lv1', mysql.FLOAT(), nullable=True),
    sa.Column('bpfi_lv2', mysql.FLOAT(), nullable=True),
    sa.Column('bpfi_lv3', mysql.FLOAT(), nullable=True),
    sa.Column('bsf_lv1', mysql.FLOAT(), nullable=True),
    sa.Column('bsf_lv2', mysql.FLOAT(), nullable=True),
    sa.Column('bsf_lv3', mysql.FLOAT(), nullable=True),
    sa.Column('bpfo_lv1', mysql.FLOAT(), nullable=True),
    sa.Column('bpfo_lv2', mysql.FLOAT(), nullable=True),
    sa.Column('bpfo_lv3', mysql.FLOAT(), nullable=True),
    sa.Column('ftf_lv1', mysql.FLOAT(), nullable=True),
    sa.Column('ftf_lv2', mysql.FLOAT(), nullable=True),
    sa.Column('ftf_lv3', mysql.FLOAT(), nullable=True),
    sa.Column('har2_lv1', mysql.FLOAT(), nullable=True),
    sa.Column('har2_lv2', mysql.FLOAT(), nullable=True),
    sa.Column('har2_lv3', mysql.FLOAT(), nullable=True),
    sa.Column('har3_lv1', mysql.FLOAT(), nullable=True),
    sa.Column('har3_lv2', mysql.FLOAT(), nullable=True),
    sa.Column('har3_lv3', mysql.FLOAT(), nullable=True),
    sa.Column('har4_lv1', mysql.FLOAT(), nullable=True),
    sa.Column('har4_lv2', mysql.FLOAT(), nullable=True),
    sa.Column('har4_lv3', mysql.FLOAT(), nullable=True),
    sa.Column('har5_lv1', mysql.FLOAT(), nullable=True),
    sa.Column('har5_lv2', mysql.FLOAT(), nullable=True),
    sa.Column('har5_lv3', mysql.FLOAT(), nullable=True),
    sa.Column('har6_lv1', mysql.FLOAT(), nullable=True),
    sa.Column('har6_lv2', mysql.FLOAT(), nullable=True),
    sa.Column('har6_lv3', mysql.FLOAT(), nullable=True),
    sa.Column('har7_lv1', mysql.FLOAT(), nullable=True),
    sa.Column('har7_lv2', mysql.FLOAT(), nullable=True),
    sa.Column('har7_lv3', mysql.FLOAT(), nullable=True),
    sa.Column('har8_lv1', mysql.FLOAT(), nullable=True),
    sa.Column('har8_lv2', mysql.FLOAT(), nullable=True),
    sa.Column('har8_lv3', mysql.FLOAT(), nullable=True),
    sa.Column('har9_lv1', mysql.FLOAT(), nullable=True),
    sa.Column('har9_lv2', mysql.FLOAT(), nullable=True),
    sa.Column('har9_lv3', mysql.FLOAT(), nullable=True),
    sa.Column('har10_lv1', mysql.FLOAT(), nullable=True),
    sa.Column('har10_lv2', mysql.FLOAT(), nullable=True),
    sa.Column('har10_lv3', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('stator_evaluate_standard')
    op.drop_table('rotor_evaluate_standard')
    op.drop_table('power_evaluate_standard')
    op.drop_table('bearing_evaluate_standard')
    # ### end Alembic commands ###
