"""first commit

Revision ID: 7b83509f58a4
Revises: 
Create Date: 2019-05-06 15:08:38.222636

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from models.models import Asset
# revision identifiers, used by Alembic.
revision = '7b83509f58a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturer',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=32), nullable=True),
                    sa.Column('telephone', sa.String(length=30), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name'),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_table('monthlyrecord',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('cr_time', sa.DateTime(), nullable=True),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_table('motor',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=True),
                    sa.Column('sn', sa.String(length=128), nullable=True),
                    sa.Column('health_indicator', sa.Float(), nullable=True),
                    sa.Column('lr_time', sa.DateTime(), nullable=True),
                    sa.Column('cr_time', sa.DateTime(), nullable=True),
                    sa.Column('md_time', sa.DateTime(), nullable=True),
                    sa.Column('equip_type', sqlalchemy_utils.types.choice.ChoiceType(Asset.TYPES), nullable=True),
                    sa.Column('memo', sa.Text(), nullable=True),
                    sa.Column('phase_number', sa.SmallInteger(), nullable=True),
                    sa.Column('pole_pairs_number', sa.SmallInteger(), nullable=True),
                    sa.Column('turn_number', sa.SmallInteger(), nullable=True),
                    sa.Column('rated_voltage', sa.Float(), nullable=True),
                    sa.Column('rated_speed', sa.Float(), nullable=True),
                    sa.Column('admin_id', sa.Integer(), nullable=True),
                    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturer.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name'),
                    sa.UniqueConstraint('sn'),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_table('bearing',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=True),
                    sa.Column('sn', sa.String(length=128), nullable=True),
                    sa.Column('health_indicator', sa.Float(), nullable=True),
                    sa.Column('lr_time', sa.DateTime(), nullable=True),
                    sa.Column('cr_time', sa.DateTime(), nullable=True),
                    sa.Column('md_time', sa.DateTime(), nullable=True),
                    sa.Column('equip_type', sqlalchemy_utils.types.choice.ChoiceType(Asset.TYPES), nullable=True),
                    sa.Column('memo', sa.Text(), nullable=True),
                    sa.Column('motor_id', sa.Integer(), nullable=True),
                    sa.Column('inner_race_diameter', sa.Float(), nullable=True),
                    sa.Column('inner_race_width', sa.Float(), nullable=True),
                    sa.Column('outter_race_diameter', sa.Float(), nullable=True),
                    sa.Column('outter_race_width', sa.Float(), nullable=True),
                    sa.Column('roller_diameter', sa.Float(), nullable=True),
                    sa.Column('roller_number', sa.SmallInteger(), nullable=True),
                    sa.Column('contact_angle', sa.Float(), nullable=True),
                    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturer.id'], ),
                    sa.ForeignKeyConstraint(['motor_id'], ['motor.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name'),
                    sa.UniqueConstraint('sn'),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_table('currentspack_0',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('time', sa.DateTime(), nullable=True),
                    sa.Column('motor_id', sa.Integer(), nullable=False),
                    sa.Column('sampling_tate', sa.Integer(), nullable=True),
                    sa.Column('rpm', sa.SmallInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['motor_id'], ['motor.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_table('currentspack_1',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('time', sa.DateTime(), nullable=True),
                    sa.Column('motor_id', sa.Integer(), nullable=False),
                    sa.Column('sampling_tate', sa.Integer(), nullable=True),
                    sa.Column('rpm', sa.SmallInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['motor_id'], ['motor.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_table('currentspack_2',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('time', sa.DateTime(), nullable=True),
                    sa.Column('motor_id', sa.Integer(), nullable=False),
                    sa.Column('sampling_tate', sa.Integer(), nullable=True),
                    sa.Column('rpm', sa.SmallInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['motor_id'], ['motor.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_table('rotor',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=True),
                    sa.Column('sn', sa.String(length=128), nullable=True),
                    sa.Column('health_indicator', sa.Float(), nullable=True),
                    sa.Column('lr_time', sa.DateTime(), nullable=True),
                    sa.Column('cr_time', sa.DateTime(), nullable=True),
                    sa.Column('md_time', sa.DateTime(), nullable=True),
                    sa.Column('equip_type', sqlalchemy_utils.types.choice.ChoiceType(Asset.TYPES), nullable=True),
                    sa.Column('memo', sa.Text(), nullable=True),
                    sa.Column('motor_id', sa.Integer(), nullable=True),
                    sa.Column('length', sa.Float(), nullable=True),
                    sa.Column('outer_diameter', sa.Float(), nullable=True),
                    sa.Column('inner_diameter', sa.Float(), nullable=True),
                    sa.Column('slot_number', sa.Integer(), nullable=True),
                    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturer.id'], ),
                    sa.ForeignKeyConstraint(['motor_id'], ['motor.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name'),
                    sa.UniqueConstraint('sn'),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_table('stator',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=True),
                    sa.Column('sn', sa.String(length=128), nullable=True),
                    sa.Column('health_indicator', sa.Float(), nullable=True),
                    sa.Column('lr_time', sa.DateTime(), nullable=True),
                    sa.Column('cr_time', sa.DateTime(), nullable=True),
                    sa.Column('md_time', sa.DateTime(), nullable=True),
                    sa.Column('equip_type', sqlalchemy_utils.types.choice.ChoiceType(Asset.TYPES), nullable=True),
                    sa.Column('memo', sa.Text(), nullable=True),
                    sa.Column('motor_id', sa.Integer(), nullable=True),
                    sa.Column('length', sa.Float(), nullable=True),
                    sa.Column('outer_diameter', sa.Float(), nullable=True),
                    sa.Column('inner_diameter', sa.Float(), nullable=True),
                    sa.Column('slot_number', sa.Integer(), nullable=True),
                    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturer.id'], ),
                    sa.ForeignKeyConstraint(['motor_id'], ['motor.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name'),
                    sa.UniqueConstraint('sn'),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_table('warninglog',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('cr_time', sa.DateTime(), nullable=True),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.Column('severity', sqlalchemy_utils.types.choice.ChoiceType(Asset.TYPES), nullable=True),
                    sa.Column('motor_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['motor_id'], ['motor.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_table('symcomponent_0',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('n_rms', sa.Float(), nullable=True),
                    sa.Column('p_rms', sa.Float(), nullable=True),
                    sa.Column('z_rms', sa.Float(), nullable=True),
                    sa.Column('imbalance', sa.Float(), nullable=True),
                    sa.Column('pack_id', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['pack_id'], ['currentspack_0.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_table('symcomponent_1',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('n_rms', sa.Float(), nullable=True),
                    sa.Column('p_rms', sa.Float(), nullable=True),
                    sa.Column('z_rms', sa.Float(), nullable=True),
                    sa.Column('imbalance', sa.Float(), nullable=True),
                    sa.Column('pack_id', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['pack_id'], ['currentspack_1.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_table('symcomponent_2',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('n_rms', sa.Float(), nullable=True),
                    sa.Column('p_rms', sa.Float(), nullable=True),
                    sa.Column('z_rms', sa.Float(), nullable=True),
                    sa.Column('imbalance', sa.Float(), nullable=True),
                    sa.Column('pack_id', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['pack_id'], ['currentspack_2.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_table('ufeature_0',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('rms', sa.Float(), nullable=True),
                    sa.Column('thd', sa.Float(), nullable=True),
                    sa.Column('harmonics', sa.LargeBinary(), nullable=True),
                    sa.Column('max_current', sa.Float(), nullable=True),
                    sa.Column('min_current', sa.Float(), nullable=True),
                    sa.Column('fbrb', sa.LargeBinary(), nullable=True),
                    sa.Column('pack_id', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['pack_id'], ['currentspack_0.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_table('ufeature_1',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('rms', sa.Float(), nullable=True),
                    sa.Column('thd', sa.Float(), nullable=True),
                    sa.Column('harmonics', sa.LargeBinary(), nullable=True),
                    sa.Column('max_current', sa.Float(), nullable=True),
                    sa.Column('min_current', sa.Float(), nullable=True),
                    sa.Column('fbrb', sa.LargeBinary(), nullable=True),
                    sa.Column('pack_id', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['pack_id'], ['currentspack_1.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_table('ufeature_2',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('rms', sa.Float(), nullable=True),
                    sa.Column('thd', sa.Float(), nullable=True),
                    sa.Column('harmonics', sa.LargeBinary(), nullable=True),
                    sa.Column('max_current', sa.Float(), nullable=True),
                    sa.Column('min_current', sa.Float(), nullable=True),
                    sa.Column('fbrb', sa.LargeBinary(), nullable=True),
                    sa.Column('pack_id', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['pack_id'], ['currentspack_2.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_table('uphase_0',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('signal', sa.LargeBinary(), nullable=False),
                    sa.Column('frequency', sa.Float(), nullable=True),
                    sa.Column('amplitude', sa.Float(), nullable=True),
                    sa.Column('initial_phase', sa.Float(), nullable=True),
                    sa.Column('pack_id', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['pack_id'], ['currentspack_0.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_table('uphase_1',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('signal', sa.LargeBinary(), nullable=False),
                    sa.Column('frequency', sa.Float(), nullable=True),
                    sa.Column('amplitude', sa.Float(), nullable=True),
                    sa.Column('initial_phase', sa.Float(), nullable=True),
                    sa.Column('pack_id', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['pack_id'], ['currentspack_1.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_table('uphase_2',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('signal', sa.LargeBinary(), nullable=False),
                    sa.Column('frequency', sa.Float(), nullable=True),
                    sa.Column('amplitude', sa.Float(), nullable=True),
                    sa.Column('initial_phase', sa.Float(), nullable=True),
                    sa.Column('pack_id', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['pack_id'], ['currentspack_2.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_table('vfeature_0',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('rms', sa.Float(), nullable=True),
                    sa.Column('thd', sa.Float(), nullable=True),
                    sa.Column('harmonics', sa.LargeBinary(), nullable=True),
                    sa.Column('max_current', sa.Float(), nullable=True),
                    sa.Column('min_current', sa.Float(), nullable=True),
                    sa.Column('fbrb', sa.LargeBinary(), nullable=True),
                    sa.Column('pack_id', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['pack_id'], ['currentspack_0.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_table('vfeature_1',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('rms', sa.Float(), nullable=True),
                    sa.Column('thd', sa.Float(), nullable=True),
                    sa.Column('harmonics', sa.LargeBinary(), nullable=True),
                    sa.Column('max_current', sa.Float(), nullable=True),
                    sa.Column('min_current', sa.Float(), nullable=True),
                    sa.Column('fbrb', sa.LargeBinary(), nullable=True),
                    sa.Column('pack_id', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['pack_id'], ['currentspack_1.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_table('vfeature_2',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('rms', sa.Float(), nullable=True),
                    sa.Column('thd', sa.Float(), nullable=True),
                    sa.Column('harmonics', sa.LargeBinary(), nullable=True),
                    sa.Column('max_current', sa.Float(), nullable=True),
                    sa.Column('min_current', sa.Float(), nullable=True),
                    sa.Column('fbrb', sa.LargeBinary(), nullable=True),
                    sa.Column('pack_id', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['pack_id'], ['currentspack_2.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_table('vphase_0',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('signal', sa.LargeBinary(), nullable=False),
                    sa.Column('frequency', sa.Float(), nullable=True),
                    sa.Column('amplitude', sa.Float(), nullable=True),
                    sa.Column('initial_phase', sa.Float(), nullable=True),
                    sa.Column('pack_id', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['pack_id'], ['currentspack_0.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_table('vphase_1',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('signal', sa.LargeBinary(), nullable=False),
                    sa.Column('frequency', sa.Float(), nullable=True),
                    sa.Column('amplitude', sa.Float(), nullable=True),
                    sa.Column('initial_phase', sa.Float(), nullable=True),
                    sa.Column('pack_id', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['pack_id'], ['currentspack_1.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_table('vphase_2',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('signal', sa.LargeBinary(), nullable=False),
                    sa.Column('frequency', sa.Float(), nullable=True),
                    sa.Column('amplitude', sa.Float(), nullable=True),
                    sa.Column('initial_phase', sa.Float(), nullable=True),
                    sa.Column('pack_id', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['pack_id'], ['currentspack_2.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_table('wfeature_0',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('rms', sa.Float(), nullable=True),
                    sa.Column('thd', sa.Float(), nullable=True),
                    sa.Column('harmonics', sa.LargeBinary(), nullable=True),
                    sa.Column('max_current', sa.Float(), nullable=True),
                    sa.Column('min_current', sa.Float(), nullable=True),
                    sa.Column('fbrb', sa.LargeBinary(), nullable=True),
                    sa.Column('pack_id', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['pack_id'], ['currentspack_0.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_table('wfeature_1',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('rms', sa.Float(), nullable=True),
                    sa.Column('thd', sa.Float(), nullable=True),
                    sa.Column('harmonics', sa.LargeBinary(), nullable=True),
                    sa.Column('max_current', sa.Float(), nullable=True),
                    sa.Column('min_current', sa.Float(), nullable=True),
                    sa.Column('fbrb', sa.LargeBinary(), nullable=True),
                    sa.Column('pack_id', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['pack_id'], ['currentspack_1.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_table('wfeature_2',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('rms', sa.Float(), nullable=True),
                    sa.Column('thd', sa.Float(), nullable=True),
                    sa.Column('harmonics', sa.LargeBinary(), nullable=True),
                    sa.Column('max_current', sa.Float(), nullable=True),
                    sa.Column('min_current', sa.Float(), nullable=True),
                    sa.Column('fbrb', sa.LargeBinary(), nullable=True),
                    sa.Column('pack_id', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['pack_id'], ['currentspack_2.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_table('wphase_0',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('signal', sa.LargeBinary(), nullable=False),
                    sa.Column('frequency', sa.Float(), nullable=True),
                    sa.Column('amplitude', sa.Float(), nullable=True),
                    sa.Column('initial_phase', sa.Float(), nullable=True),
                    sa.Column('pack_id', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['pack_id'], ['currentspack_0.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_table('wphase_1',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('signal', sa.LargeBinary(), nullable=False),
                    sa.Column('frequency', sa.Float(), nullable=True),
                    sa.Column('amplitude', sa.Float(), nullable=True),
                    sa.Column('initial_phase', sa.Float(), nullable=True),
                    sa.Column('pack_id', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['pack_id'], ['currentspack_1.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_table('wphase_2',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('signal', sa.LargeBinary(), nullable=False),
                    sa.Column('frequency', sa.Float(), nullable=True),
                    sa.Column('amplitude', sa.Float(), nullable=True),
                    sa.Column('initial_phase', sa.Float(), nullable=True),
                    sa.Column('pack_id', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['pack_id'], ['currentspack_2.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wphase_2')
    op.drop_table('wphase_1')
    op.drop_table('wphase_0')
    op.drop_table('wfeature_2')
    op.drop_table('wfeature_1')
    op.drop_table('wfeature_0')
    op.drop_table('vphase_2')
    op.drop_table('vphase_1')
    op.drop_table('vphase_0')
    op.drop_table('vfeature_2')
    op.drop_table('vfeature_1')
    op.drop_table('vfeature_0')
    op.drop_table('uphase_2')
    op.drop_table('uphase_1')
    op.drop_table('uphase_0')
    op.drop_table('ufeature_2')
    op.drop_table('ufeature_1')
    op.drop_table('ufeature_0')
    op.drop_table('symcomponent_2')
    op.drop_table('symcomponent_1')
    op.drop_table('symcomponent_0')
    op.drop_table('warninglog')
    op.drop_table('stator')
    op.drop_table('rotor')
    op.drop_table('currentspack_2')
    op.drop_table('currentspack_1')
    op.drop_table('currentspack_0')
    op.drop_table('bearing')
    op.drop_table('motor')
    op.drop_table('user')
    op.drop_table('monthlyrecord')
    op.drop_table('manufacturer')
    # ### end Alembic commands ###
