"""modify for diagnosis

Revision ID: ee0e92c453fe
Revises: 86c6c040aef6
Create Date: 2019-07-09 19:01:53.078486

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ee0e92c453fe'
down_revision = '86c6c040aef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motor_evaluate_standard',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('imbalance_lv1', sa.Float(), nullable=True),
                    sa.Column('imbalance_lv2', sa.Float(), nullable=True),
                    sa.Column('imbalance_lv3', sa.Float(), nullable=True),
                    sa.Column('thd_lv1', sa.Float(), nullable=True),
                    sa.Column('thd_lv2', sa.Float(), nullable=True),
                    sa.Column('thd_lv3', sa.Float(), nullable=True),
                    sa.Column('brb_lv1', sa.Float(), nullable=True),
                    sa.Column('brb_lv2', sa.Float(), nullable=True),
                    sa.Column('brb_lv3', sa.Float(), nullable=True),
                    sa.Column('bpfi_lv1', sa.Float(), nullable=True),
                    sa.Column('bpfi_lv2', sa.Float(), nullable=True),
                    sa.Column('bpfi_lv3', sa.Float(), nullable=True),
                    sa.Column('bsf_lv1', sa.Float(), nullable=True),
                    sa.Column('bsf_lv2', sa.Float(), nullable=True),
                    sa.Column('bsf_lv3', sa.Float(), nullable=True),
                    sa.Column('bpfo_lv1', sa.Float(), nullable=True),
                    sa.Column('bpfo_lv2', sa.Float(), nullable=True),
                    sa.Column('bpfo_lv3', sa.Float(), nullable=True),
                    sa.Column('ftf_lv1', sa.Float(), nullable=True),
                    sa.Column('ftf_lv2', sa.Float(), nullable=True),
                    sa.Column('ftf_lv3', sa.Float(), nullable=True),
                    sa.Column('har2_lv1', sa.Float(), nullable=True),
                    sa.Column('har2_lv2', sa.Float(), nullable=True),
                    sa.Column('har2_lv3', sa.Float(), nullable=True),
                    sa.Column('har3_lv1', sa.Float(), nullable=True),
                    sa.Column('har3_lv2', sa.Float(), nullable=True),
                    sa.Column('har3_lv3', sa.Float(), nullable=True),
                    sa.Column('har4_lv1', sa.Float(), nullable=True),
                    sa.Column('har4_lv2', sa.Float(), nullable=True),
                    sa.Column('har4_lv3', sa.Float(), nullable=True),
                    sa.Column('har5_lv1', sa.Float(), nullable=True),
                    sa.Column('har5_lv2', sa.Float(), nullable=True),
                    sa.Column('har5_lv3', sa.Float(), nullable=True),
                    sa.Column('har6_lv1', sa.Float(), nullable=True),
                    sa.Column('har6_lv2', sa.Float(), nullable=True),
                    sa.Column('har6_lv3', sa.Float(), nullable=True),
                    sa.Column('har7_lv1', sa.Float(), nullable=True),
                    sa.Column('har7_lv2', sa.Float(), nullable=True),
                    sa.Column('har7_lv3', sa.Float(), nullable=True),
                    sa.Column('har8_lv1', sa.Float(), nullable=True),
                    sa.Column('har8_lv2', sa.Float(), nullable=True),
                    sa.Column('har8_lv3', sa.Float(), nullable=True),
                    sa.Column('har9_lv1', sa.Float(), nullable=True),
                    sa.Column('har9_lv2', sa.Float(), nullable=True),
                    sa.Column('har9_lv3', sa.Float(), nullable=True),
                    sa.Column('har10_lv1', sa.Float(), nullable=True),
                    sa.Column('har10_lv2', sa.Float(), nullable=True),
                    sa.Column('har10_lv3', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.add_column('bearing', sa.Column('bpfi', sa.Float(), nullable=True))
    op.add_column('bearing', sa.Column('bpfo', sa.Float(), nullable=True))
    op.add_column('bearing', sa.Column('bsf', sa.Float(), nullable=True))
    op.add_column('bearing', sa.Column('ftf', sa.Float(), nullable=True))
    op.add_column('feature_0', sa.Column('health_indicator', sa.Float(), nullable=True))
    op.add_column('feature_1', sa.Column('health_indicator', sa.Float(), nullable=True))
    op.add_column('feature_2', sa.Column('health_indicator', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feature_2', 'health_indicator')
    op.drop_column('feature_1', 'health_indicator')
    op.drop_column('feature_0', 'health_indicator')

    op.drop_column('bearing', 'ftf')
    op.drop_column('bearing', 'bsf')
    op.drop_column('bearing', 'bpfo')
    op.drop_column('bearing', 'bpfi')
    op.drop_table('motor_evaluate_standard')
    # ### end Alembic commands ###
